<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.cryptomator</groupId>
	<artifactId>jfuse-parent</artifactId>
	<packaging>pom</packaging>
	<version>0.8.0-SNAPSHOT</version>
	<name>jFUSE</name>
	<description>Java bindings for FUSE using foreign functions &amp; memory API</description>
	<url>https://github.com/cryptomator/jfuse</url>

	<licenses>
		<license>
			<name>GNU Lesser General Public License (LGPLV3+)</name>
			<url>http://www.gnu.org/licenses/lgpl-3.0.html</url>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<developers>
		<developer>
			<name>Sebastian Stenzel</name>
			<email>sebastian.stenzel@gmail.com</email>
			<timezone>+1</timezone>
			<organization>cryptomator.org</organization>
			<organizationUrl>http://cryptomator.org</organizationUrl>
		</developer>
	</developers>

	<scm>
		<connection>scm:git:git@github.com:cryptomator/jfuse.git</connection>
		<developerConnection>scm:git:git@github.com:cryptomator/jfuse.git</developerConnection>
		<url>https://github.com/cryptomator/jfuse</url>
	</scm>

	<properties>
		<maven.deploy.skip>false</maven.deploy.skip>
		<java.version>25</java.version>
		<jextract.path>${user.home}/.sdkman/candidates/jextract/current/bin/jextract</jextract.path>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<jb-annotations.version>26.0.2-1</jb-annotations.version>

		<!-- test dependencies -->
		<junit.version>6.0.2</junit.version>
		<mockito.version>5.21.0</mockito.version>

		<!-- build-time dependencies -->
		<license-generator.version>2.7.0</license-generator.version>
		<exec-maven.version>3.5.1</exec-maven.version>

		<central-publishing.version>0.8.0</central-publishing.version>
		<jacoco.version>0.8.14</jacoco.version>
		<jextract.version>0.4.3</jextract.version>
		<junit-tree-reporter.version>1.4.0</junit-tree-reporter.version>
		<mvn-clean.version>3.5.0</mvn-clean.version>
		<mvn-compiler.version>3.14.1</mvn-compiler.version>
		<mvn-dependency.version>3.8.1</mvn-dependency.version>
		<mvn-deploy.version>3.1.4</mvn-deploy.version>
		<mvn-enforcer.version>3.6.1</mvn-enforcer.version>
		<mvn-failsafe.version>3.5.4</mvn-failsafe.version>
		<mvn-javadoc.version>3.11.3</mvn-javadoc.version>
		<mvn-jar.version>3.5.0</mvn-jar.version>
		<mvn-gpg.version>3.2.8</mvn-gpg.version>
		<mvn-resources.version>3.3.1</mvn-resources.version>
		<mvn-source.version>3.3.1</mvn-source.version>
		<mvn-surefire.version>3.5.4</mvn-surefire.version>

		<!-- Property used by surefire to determine jacoco engine -->
		<surefire.jacoco.args></surefire.jacoco.args>
	</properties>

	<modules>
		<module>jfuse-api</module>
		<module>jfuse-linux-aarch64</module>
		<module>jfuse-linux-amd64</module>
		<module>jfuse-mac</module>
		<module>jfuse-win</module>
		<module>jfuse</module>
	</modules>

	<dependencies>
		<dependency>
			<groupId>org.jetbrains</groupId>
			<artifactId>annotations</artifactId>
			<version>${jb-annotations.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>${mockito.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-dependency-plugin</artifactId>
					<version>${mvn-dependency.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.14.1</version>
					<configuration>
						<release>${java.version}</release>
						<encoding>UTF-8</encoding>
						<showWarnings>true</showWarnings>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-enforcer-plugin</artifactId>
					<version>${mvn-enforcer.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-clean-plugin</artifactId>
					<version>${mvn-clean.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-gpg-plugin</artifactId>
					<version>${mvn-gpg.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<version>${mvn-jar.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-source-plugin</artifactId>
					<version>${mvn-source.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-javadoc-plugin</artifactId>
					<version>${mvn-javadoc.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>${mvn-surefire.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-failsafe-plugin</artifactId>
					<version>${mvn-failsafe.version}</version>
				</plugin>
				<plugin>
					<groupId>org.sonatype.central</groupId>
					<artifactId>central-publishing-maven-plugin</artifactId>
					<version>${central-publishing.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-deploy-plugin</artifactId>
					<version>${mvn-deploy.version}</version>
				</plugin>
				<plugin>
					<groupId>org.jacoco</groupId>
					<artifactId>jacoco-maven-plugin</artifactId>
					<version>${jacoco.version}</version>
				</plugin>
			</plugins>
		</pluginManagement>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>jar-paths-to-properties</id>
						<goals>
							<goal>properties</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar-no-fork</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<executions>
					<execution>
						<id>attach-javadocs</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<excludePackageNames>*.extr:*.extr.*</excludePackageNames>
					<release>${java.version}</release>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>prepare-agent</id>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
						<configuration>
							<propertyName>surefire.jacoco.args</propertyName>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<configuration>
					<argLine>@{surefire.jacoco.args} -javaagent:"${org.mockito:mockito-core:jar}"</argLine>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>test</id>
			<activation>
				<property>
					<name>!skipTests</name>
				</property>
			</activation>
			<modules>
				<module>jfuse-examples</module>
				<module>jfuse-tests</module>
			</modules>
		</profile>

		<profile>
			<id>sign</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-gpg-plugin</artifactId>
						<executions>
							<execution>
								<id>sign-artifacts</id>
								<phase>verify</phase>
								<goals>
									<goal>sign</goal>
								</goals>
								<configuration>
									<signer>bc</signer>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>deploy-central</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.sonatype.central</groupId>
 						<artifactId>central-publishing-maven-plugin</artifactId>
						<extensions>true</extensions>
						<configuration>
							<publishingServerId>central</publishingServerId>
  							<autoPublish>true</autoPublish>
							<skipPublishing>${maven.deploy.skip}</skipPublishing>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>deploy-github</id>
			<distributionManagement>
				<repository>
					<id>github</id>
					<name>GitHub Packages</name>
					<url>https://maven.pkg.github.com/cryptomator/jfuse</url>
				</repository>
			</distributionManagement>
		</profile>
	</profiles>

</project>