// Generated by jextract

package org.cryptomator.jfuse.mac.extr.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$22 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$22() {}
    static final VarHandle const$0 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("opendir"));
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(fuse_operations.readdir.class, "apply", constants$22.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$22.const$1
    );
    static final VarHandle const$4 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("readdir"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(fuse_operations.releasedir.class, "apply", constants$9.const$5);
}


