// Generated by jextract

package org.cryptomator.jfuse.mac.extr.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2() {}
    static final VarHandle const$0 = constants$1.const$4.varHandle(MemoryLayout.PathElement.groupElement("proto_minor"));
    static final VarHandle const$1 = constants$1.const$4.varHandle(MemoryLayout.PathElement.groupElement("async_read"));
    static final VarHandle const$2 = constants$1.const$4.varHandle(MemoryLayout.PathElement.groupElement("max_write"));
    static final VarHandle const$3 = constants$1.const$4.varHandle(MemoryLayout.PathElement.groupElement("max_readahead"));
    static final VarHandle const$4 = constants$1.const$4.varHandle(MemoryLayout.PathElement.groupElement("capable"));
    static final VarHandle const$5 = constants$1.const$4.varHandle(MemoryLayout.PathElement.groupElement("want"));
}


