// Generated by jextract

package org.cryptomator.jfuse.mac.extr.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$28 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$28() {}
    static final VarHandle const$0 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("utimens"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(fuse_operations.bmap.class, "apply", constants$26.const$1);
    static final VarHandle const$2 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("bmap"));
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(fuse_operations.ioctl.class, "apply", constants$28.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$28.const$3
    );
}


