// Generated by jextract

package org.cryptomator.jfuse.mac.extr.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "fuse_parse_cmdline",
        constants$4.const$0
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_LONG.withName("tv_sec"),
        JAVA_LONG.withName("tv_nsec")
    ).withName("timespec");
    static final VarHandle const$3 = constants$4.const$2.varHandle(MemoryLayout.PathElement.groupElement("tv_sec"));
    static final VarHandle const$4 = constants$4.const$2.varHandle(MemoryLayout.PathElement.groupElement("tv_nsec"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("st_dev"),
        JAVA_SHORT.withName("st_mode"),
        JAVA_SHORT.withName("st_nlink"),
        JAVA_LONG.withName("st_ino"),
        JAVA_INT.withName("st_uid"),
        JAVA_INT.withName("st_gid"),
        JAVA_INT.withName("st_rdev"),
        MemoryLayout.paddingLayout(4),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_nsec")
        ).withName("st_atimespec"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_nsec")
        ).withName("st_mtimespec"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_nsec")
        ).withName("st_ctimespec"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_nsec")
        ).withName("st_birthtimespec"),
        JAVA_LONG.withName("st_size"),
        JAVA_LONG.withName("st_blocks"),
        JAVA_INT.withName("st_blksize"),
        JAVA_INT.withName("st_flags"),
        JAVA_INT.withName("st_gen"),
        JAVA_INT.withName("st_lspare"),
        MemoryLayout.sequenceLayout(2, JAVA_LONG).withName("st_qspare")
    ).withName("stat");
}


