// Generated by jextract

package org.cryptomator.jfuse.mac.extr.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {}
    static final VarHandle const$0 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("st_rdev"));
    static final VarHandle const$1 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("st_size"));
    static final VarHandle const$2 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("st_blocks"));
    static final VarHandle const$3 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("st_blksize"));
    static final VarHandle const$4 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("st_flags"));
    static final VarHandle const$5 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("st_gen"));
}


