// Generated by jextract

package org.cryptomator.jfuse.mac.extr.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct fuse_file_info {
 *     int flags;
 *     unsigned long fh_old;
 *     int writepage;
 *      *     unsigned int direct_io;
 *     unsigned int keep_cache;
 *     unsigned int flush;
 *     unsigned int nonseekable;
 *     unsigned int flock_release;
 *     unsigned int padding;
 *     uint64_t fh;
 *     uint64_t lock_owner;
 * };
 * }
 */
public class fuse_file_info {

    public static MemoryLayout $LAYOUT() {
        return constants$0.const$4;
    }
    public static VarHandle flags$VH() {
        return constants$0.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int flags;
     * }
     */
    public static int flags$get(MemorySegment seg) {
        return (int)constants$0.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int flags;
     * }
     */
    public static void flags$set(MemorySegment seg, int x) {
        constants$0.const$5.set(seg, x);
    }
    public static int flags$get(MemorySegment seg, long index) {
        return (int)constants$0.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void flags$set(MemorySegment seg, long index, int x) {
        constants$0.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle fh_old$VH() {
        return constants$1.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned long fh_old;
     * }
     */
    public static long fh_old$get(MemorySegment seg) {
        return (long)constants$1.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned long fh_old;
     * }
     */
    public static void fh_old$set(MemorySegment seg, long x) {
        constants$1.const$0.set(seg, x);
    }
    public static long fh_old$get(MemorySegment seg, long index) {
        return (long)constants$1.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void fh_old$set(MemorySegment seg, long index, long x) {
        constants$1.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle writepage$VH() {
        return constants$1.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int writepage;
     * }
     */
    public static int writepage$get(MemorySegment seg) {
        return (int)constants$1.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int writepage;
     * }
     */
    public static void writepage$set(MemorySegment seg, int x) {
        constants$1.const$1.set(seg, x);
    }
    public static int writepage$get(MemorySegment seg, long index) {
        return (int)constants$1.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void writepage$set(MemorySegment seg, long index, int x) {
        constants$1.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle fh$VH() {
        return constants$1.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t fh;
     * }
     */
    public static long fh$get(MemorySegment seg) {
        return (long)constants$1.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t fh;
     * }
     */
    public static void fh$set(MemorySegment seg, long x) {
        constants$1.const$2.set(seg, x);
    }
    public static long fh$get(MemorySegment seg, long index) {
        return (long)constants$1.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void fh$set(MemorySegment seg, long index, long x) {
        constants$1.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle lock_owner$VH() {
        return constants$1.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t lock_owner;
     * }
     */
    public static long lock_owner$get(MemorySegment seg) {
        return (long)constants$1.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t lock_owner;
     * }
     */
    public static void lock_owner$set(MemorySegment seg, long x) {
        constants$1.const$3.set(seg, x);
    }
    public static long lock_owner$get(MemorySegment seg, long index) {
        return (long)constants$1.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void lock_owner$set(MemorySegment seg, long index, long x) {
        constants$1.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


