// Generated by jextract

package de.skymatic.fusepanama.linux.lowlevel;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class errno_h  {

    static {
    }

    static final SymbolLookup LIBRARIES = RuntimeHelper.lookup();    /* package-private */ errno_h() {}
    public static int ENOENT() {
        return (int)2L;
    }
    public static int ENOSYS() {
        return (int)38L;
    }
}


