// Generated by jextract

package de.skymatic.fusepanama.linux.amd64.lowlevel;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class fcntl_h  {

    /* package-private */ fcntl_h() {}
    public static OfByte C_CHAR = Constants$root.C_CHAR$LAYOUT;
    public static OfShort C_SHORT = Constants$root.C_SHORT$LAYOUT;
    public static OfInt C_INT = Constants$root.C_INT$LAYOUT;
    public static OfLong C_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static OfLong C_LONG_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static OfFloat C_FLOAT = Constants$root.C_FLOAT$LAYOUT;
    public static OfDouble C_DOUBLE = Constants$root.C_DOUBLE$LAYOUT;
    public static OfAddress C_POINTER = Constants$root.C_POINTER$LAYOUT;
    public static int O_RDONLY() {
        return (int)0L;
    }
    public static int O_WRONLY() {
        return (int)1L;
    }
    public static int O_RDWR() {
        return (int)2L;
    }
    public static int O_CREAT() {
        return (int)64L;
    }
    public static int O_EXCL() {
        return (int)128L;
    }
    public static int O_TRUNC() {
        return (int)512L;
    }
    public static int O_APPEND() {
        return (int)1024L;
    }
    public static int O_SYNC() {
        return (int)1052672L;
    }
    public static int O_DSYNC() {
        return (int)4096L;
    }
}


