// Generated by jextract

package org.cryptomator.jfuse.linux.aarch64.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$10 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$10() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(fuse_fill_dir_t.class, "apply", constants$10.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$10.const$0
    );
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("set_gid"),
        JAVA_INT.withName("gid"),
        JAVA_INT.withName("set_uid"),
        JAVA_INT.withName("uid"),
        JAVA_INT.withName("set_mode"),
        JAVA_INT.withName("umask"),
        JAVA_DOUBLE.withName("entry_timeout"),
        JAVA_DOUBLE.withName("negative_timeout"),
        JAVA_DOUBLE.withName("attr_timeout"),
        JAVA_INT.withName("intr"),
        JAVA_INT.withName("intr_signal"),
        JAVA_INT.withName("remember"),
        JAVA_INT.withName("hard_remove"),
        JAVA_INT.withName("use_ino"),
        JAVA_INT.withName("readdir_ino"),
        JAVA_INT.withName("direct_io"),
        JAVA_INT.withName("kernel_cache"),
        JAVA_INT.withName("auto_cache"),
        JAVA_INT.withName("no_rofd_flush"),
        JAVA_INT.withName("ac_attr_timeout_set"),
        MemoryLayout.paddingLayout(4),
        JAVA_DOUBLE.withName("ac_attr_timeout"),
        JAVA_INT.withName("nullpath_ok"),
        JAVA_INT.withName("show_help"),
        RuntimeHelper.POINTER.withName("modules"),
        JAVA_INT.withName("debug"),
        MemoryLayout.paddingLayout(4)
    ).withName("fuse_config");
    static final VarHandle const$4 = constants$10.const$3.varHandle(MemoryLayout.PathElement.groupElement("set_gid"));
    static final VarHandle const$5 = constants$10.const$3.varHandle(MemoryLayout.PathElement.groupElement("gid"));
}


