// Generated by jextract

package org.cryptomator.jfuse.linux.aarch64.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$31 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$31() {}
    static final VarHandle const$0 = constants$14.const$5.varHandle(MemoryLayout.PathElement.groupElement("utimens"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(fuse_operations.bmap.class, "apply", constants$21.const$4);
    static final VarHandle const$2 = constants$14.const$5.varHandle(MemoryLayout.PathElement.groupElement("bmap"));
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(fuse_operations.ioctl.class, "apply", constants$31.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$31.const$3
    );
}


