// Generated by jextract

package org.cryptomator.jfuse.linux.aarch64.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$29 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$29() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(fuse_operations.destroy.class, "apply", constants$5.const$0);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$5.const$0
    );
    static final VarHandle const$2 = constants$14.const$5.varHandle(MemoryLayout.PathElement.groupElement("destroy"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(fuse_operations.access.class, "apply", constants$17.const$0);
    static final VarHandle const$4 = constants$14.const$5.varHandle(MemoryLayout.PathElement.groupElement("access"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(fuse_operations.create.class, "apply", constants$20.const$2);
}


