// Generated by jextract

package org.cryptomator.jfuse.linux.aarch64.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$26 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$26() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(fuse_operations.listxattr.class, "apply", constants$15.const$4);
    static final VarHandle const$1 = constants$14.const$5.varHandle(MemoryLayout.PathElement.groupElement("listxattr"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(fuse_operations.removexattr.class, "apply", constants$18.const$4);
    static final VarHandle const$3 = constants$14.const$5.varHandle(MemoryLayout.PathElement.groupElement("removexattr"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(fuse_operations.opendir.class, "apply", constants$18.const$4);
    static final VarHandle const$5 = constants$14.const$5.varHandle(MemoryLayout.PathElement.groupElement("opendir"));
}


