// Generated by jextract

package org.cryptomator.jfuse.linux.aarch64.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4() {}
    static final VarHandle const$0 = constants$2.const$3.varHandle(MemoryLayout.PathElement.groupElement("congestion_threshold"));
    static final VarHandle const$1 = constants$2.const$3.varHandle(MemoryLayout.PathElement.groupElement("time_gran"));
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "fuse_version",
        constants$4.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(RuntimeHelper.POINTER);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "fuse_loop_cfg_create",
        constants$4.const$4
    );
}


