// Generated by jextract

package org.cryptomator.jfuse.linux.aarch64.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$27 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$27() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(fuse_operations.readdir.class, "apply", constants$27.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$27.const$0
    );
    static final VarHandle const$3 = constants$14.const$5.varHandle(MemoryLayout.PathElement.groupElement("readdir"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(fuse_operations.releasedir.class, "apply", constants$18.const$4);
    static final VarHandle const$5 = constants$14.const$5.varHandle(MemoryLayout.PathElement.groupElement("releasedir"));
}


