// Generated by jextract

package org.cryptomator.jfuse.linux.aarch64.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class fuse_h  {

    public static final OfByte C_CHAR = JAVA_BYTE;
    public static final OfShort C_SHORT = JAVA_SHORT;
    public static final OfInt C_INT = JAVA_INT;
    public static final OfLong C_LONG = JAVA_LONG;
    public static final OfLong C_LONG_LONG = JAVA_LONG;
    public static final OfFloat C_FLOAT = JAVA_FLOAT;
    public static final OfDouble C_DOUBLE = JAVA_DOUBLE;
    public static final AddressLayout C_POINTER = RuntimeHelper.POINTER;
    public static MethodHandle fuse_version$MH() {
        return RuntimeHelper.requireNonNull(constants$4.const$3,"fuse_version");
    }
    /**
     * {@snippet :
     * int fuse_version();
     * }
     */
    public static int fuse_version() {
        var mh$ = fuse_version$MH();
        try {
            return (int)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle fuse_loop_cfg_create$MH() {
        return RuntimeHelper.requireNonNull(constants$4.const$5,"fuse_loop_cfg_create");
    }
    /**
     * {@snippet :
     * struct fuse_loop_config* fuse_loop_cfg_create();
     * }
     */
    public static MemorySegment fuse_loop_cfg_create() {
        var mh$ = fuse_loop_cfg_create$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle fuse_loop_cfg_destroy$MH() {
        return RuntimeHelper.requireNonNull(constants$5.const$1,"fuse_loop_cfg_destroy");
    }
    /**
     * {@snippet :
     * void fuse_loop_cfg_destroy(struct fuse_loop_config* config);
     * }
     */
    public static void fuse_loop_cfg_destroy(MemorySegment config) {
        var mh$ = fuse_loop_cfg_destroy$MH();
        try {
            mh$.invokeExact(config);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle fuse_loop_cfg_set_max_threads$MH() {
        return RuntimeHelper.requireNonNull(constants$5.const$3,"fuse_loop_cfg_set_max_threads");
    }
    /**
     * {@snippet :
     * void fuse_loop_cfg_set_max_threads(struct fuse_loop_config* config, unsigned int value);
     * }
     */
    public static void fuse_loop_cfg_set_max_threads(MemorySegment config, int value) {
        var mh$ = fuse_loop_cfg_set_max_threads$MH();
        try {
            mh$.invokeExact(config, value);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle fuse_loop_cfg_set_clone_fd$MH() {
        return RuntimeHelper.requireNonNull(constants$5.const$4,"fuse_loop_cfg_set_clone_fd");
    }
    /**
     * {@snippet :
     * void fuse_loop_cfg_set_clone_fd(struct fuse_loop_config* config, unsigned int value);
     * }
     */
    public static void fuse_loop_cfg_set_clone_fd(MemorySegment config, int value) {
        var mh$ = fuse_loop_cfg_set_clone_fd$MH();
        try {
            mh$.invokeExact(config, value);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle fuse_lib_help$MH() {
        return RuntimeHelper.requireNonNull(constants$36.const$1,"fuse_lib_help");
    }
    /**
     * {@snippet :
     * void fuse_lib_help(struct fuse_args* args);
     * }
     */
    public static void fuse_lib_help(MemorySegment args) {
        var mh$ = fuse_lib_help$MH();
        try {
            mh$.invokeExact(args);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle fuse_new$MH() {
        return RuntimeHelper.requireNonNull(constants$36.const$3,"fuse_new");
    }
    /**
     * {@snippet :
     * struct fuse* fuse_new(struct fuse_args* args, struct fuse_operations* op, unsigned long op_size, void* private_data);
     * }
     */
    public static MemorySegment fuse_new(MemorySegment args, MemorySegment op, long op_size, MemorySegment private_data) {
        var mh$ = fuse_new$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(args, op, op_size, private_data);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle fuse_mount$MH() {
        return RuntimeHelper.requireNonNull(constants$36.const$4,"fuse_mount");
    }
    /**
     * {@snippet :
     * int fuse_mount(struct fuse* f, char* mountpoint);
     * }
     */
    public static int fuse_mount(MemorySegment f, MemorySegment mountpoint) {
        var mh$ = fuse_mount$MH();
        try {
            return (int)mh$.invokeExact(f, mountpoint);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle fuse_unmount$MH() {
        return RuntimeHelper.requireNonNull(constants$36.const$5,"fuse_unmount");
    }
    /**
     * {@snippet :
     * void fuse_unmount(struct fuse* f);
     * }
     */
    public static void fuse_unmount(MemorySegment f) {
        var mh$ = fuse_unmount$MH();
        try {
            mh$.invokeExact(f);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle fuse_destroy$MH() {
        return RuntimeHelper.requireNonNull(constants$37.const$0,"fuse_destroy");
    }
    /**
     * {@snippet :
     * void fuse_destroy(struct fuse* f);
     * }
     */
    public static void fuse_destroy(MemorySegment f) {
        var mh$ = fuse_destroy$MH();
        try {
            mh$.invokeExact(f);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle fuse_loop$MH() {
        return RuntimeHelper.requireNonNull(constants$37.const$1,"fuse_loop");
    }
    /**
     * {@snippet :
     * int fuse_loop(struct fuse* f);
     * }
     */
    public static int fuse_loop(MemorySegment f) {
        var mh$ = fuse_loop$MH();
        try {
            return (int)mh$.invokeExact(f);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle fuse_exit$MH() {
        return RuntimeHelper.requireNonNull(constants$37.const$2,"fuse_exit");
    }
    /**
     * {@snippet :
     * void fuse_exit(struct fuse* f);
     * }
     */
    public static void fuse_exit(MemorySegment f) {
        var mh$ = fuse_exit$MH();
        try {
            mh$.invokeExact(f);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle fuse_loop_mt$MH() {
        return RuntimeHelper.requireNonNull(constants$37.const$3,"fuse_loop_mt");
    }
    /**
     * {@snippet :
     * int fuse_loop_mt(struct fuse* f, struct fuse_loop_config* config);
     * }
     */
    public static int fuse_loop_mt(MemorySegment f, MemorySegment config) {
        var mh$ = fuse_loop_mt$MH();
        try {
            return (int)mh$.invokeExact(f, config);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle fuse_get_session$MH() {
        return RuntimeHelper.requireNonNull(constants$37.const$5,"fuse_get_session");
    }
    /**
     * {@snippet :
     * struct fuse_session* fuse_get_session(struct fuse* f);
     * }
     */
    public static MemorySegment fuse_get_session(MemorySegment f) {
        var mh$ = fuse_get_session$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(f);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}


