// Generated by jextract

package de.skymatic.fusepanama.mac.lowlevel;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class fuse_conn_info {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        C_INT.withName("proto_major"),
        C_INT.withName("proto_minor"),
        C_INT.withName("async_read"),
        C_INT.withName("max_write"),
        C_INT.withName("max_readahead"),
        C_INT.withName("capable"),
        C_INT.withName("want"),
        C_INT.withName("max_background"),
        C_INT.withName("congestion_threshold"),
        MemoryLayout.sequenceLayout(23, C_INT).withName("reserved")
    ).withName("fuse_conn_info");
    public static MemoryLayout $LAYOUT() {
        return fuse_conn_info.$struct$LAYOUT;
    }
    static final VarHandle proto_major$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("proto_major"));
    public static VarHandle proto_major$VH() {
        return fuse_conn_info.proto_major$VH;
    }
    public static int proto_major$get(MemorySegment seg) {
        return (int)fuse_conn_info.proto_major$VH.get(seg);
    }
    public static void proto_major$set( MemorySegment seg, int x) {
        fuse_conn_info.proto_major$VH.set(seg, x);
    }
    public static int proto_major$get(MemorySegment seg, long index) {
        return (int)fuse_conn_info.proto_major$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void proto_major$set(MemorySegment seg, long index, int x) {
        fuse_conn_info.proto_major$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle proto_minor$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("proto_minor"));
    public static VarHandle proto_minor$VH() {
        return fuse_conn_info.proto_minor$VH;
    }
    public static int proto_minor$get(MemorySegment seg) {
        return (int)fuse_conn_info.proto_minor$VH.get(seg);
    }
    public static void proto_minor$set( MemorySegment seg, int x) {
        fuse_conn_info.proto_minor$VH.set(seg, x);
    }
    public static int proto_minor$get(MemorySegment seg, long index) {
        return (int)fuse_conn_info.proto_minor$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void proto_minor$set(MemorySegment seg, long index, int x) {
        fuse_conn_info.proto_minor$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle async_read$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("async_read"));
    public static VarHandle async_read$VH() {
        return fuse_conn_info.async_read$VH;
    }
    public static int async_read$get(MemorySegment seg) {
        return (int)fuse_conn_info.async_read$VH.get(seg);
    }
    public static void async_read$set( MemorySegment seg, int x) {
        fuse_conn_info.async_read$VH.set(seg, x);
    }
    public static int async_read$get(MemorySegment seg, long index) {
        return (int)fuse_conn_info.async_read$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void async_read$set(MemorySegment seg, long index, int x) {
        fuse_conn_info.async_read$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle max_write$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("max_write"));
    public static VarHandle max_write$VH() {
        return fuse_conn_info.max_write$VH;
    }
    public static int max_write$get(MemorySegment seg) {
        return (int)fuse_conn_info.max_write$VH.get(seg);
    }
    public static void max_write$set( MemorySegment seg, int x) {
        fuse_conn_info.max_write$VH.set(seg, x);
    }
    public static int max_write$get(MemorySegment seg, long index) {
        return (int)fuse_conn_info.max_write$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void max_write$set(MemorySegment seg, long index, int x) {
        fuse_conn_info.max_write$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle max_readahead$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("max_readahead"));
    public static VarHandle max_readahead$VH() {
        return fuse_conn_info.max_readahead$VH;
    }
    public static int max_readahead$get(MemorySegment seg) {
        return (int)fuse_conn_info.max_readahead$VH.get(seg);
    }
    public static void max_readahead$set( MemorySegment seg, int x) {
        fuse_conn_info.max_readahead$VH.set(seg, x);
    }
    public static int max_readahead$get(MemorySegment seg, long index) {
        return (int)fuse_conn_info.max_readahead$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void max_readahead$set(MemorySegment seg, long index, int x) {
        fuse_conn_info.max_readahead$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle capable$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("capable"));
    public static VarHandle capable$VH() {
        return fuse_conn_info.capable$VH;
    }
    public static int capable$get(MemorySegment seg) {
        return (int)fuse_conn_info.capable$VH.get(seg);
    }
    public static void capable$set( MemorySegment seg, int x) {
        fuse_conn_info.capable$VH.set(seg, x);
    }
    public static int capable$get(MemorySegment seg, long index) {
        return (int)fuse_conn_info.capable$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void capable$set(MemorySegment seg, long index, int x) {
        fuse_conn_info.capable$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle want$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("want"));
    public static VarHandle want$VH() {
        return fuse_conn_info.want$VH;
    }
    public static int want$get(MemorySegment seg) {
        return (int)fuse_conn_info.want$VH.get(seg);
    }
    public static void want$set( MemorySegment seg, int x) {
        fuse_conn_info.want$VH.set(seg, x);
    }
    public static int want$get(MemorySegment seg, long index) {
        return (int)fuse_conn_info.want$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void want$set(MemorySegment seg, long index, int x) {
        fuse_conn_info.want$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle max_background$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("max_background"));
    public static VarHandle max_background$VH() {
        return fuse_conn_info.max_background$VH;
    }
    public static int max_background$get(MemorySegment seg) {
        return (int)fuse_conn_info.max_background$VH.get(seg);
    }
    public static void max_background$set( MemorySegment seg, int x) {
        fuse_conn_info.max_background$VH.set(seg, x);
    }
    public static int max_background$get(MemorySegment seg, long index) {
        return (int)fuse_conn_info.max_background$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void max_background$set(MemorySegment seg, long index, int x) {
        fuse_conn_info.max_background$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle congestion_threshold$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("congestion_threshold"));
    public static VarHandle congestion_threshold$VH() {
        return fuse_conn_info.congestion_threshold$VH;
    }
    public static int congestion_threshold$get(MemorySegment seg) {
        return (int)fuse_conn_info.congestion_threshold$VH.get(seg);
    }
    public static void congestion_threshold$set( MemorySegment seg, int x) {
        fuse_conn_info.congestion_threshold$VH.set(seg, x);
    }
    public static int congestion_threshold$get(MemorySegment seg, long index) {
        return (int)fuse_conn_info.congestion_threshold$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void congestion_threshold$set(MemorySegment seg, long index, int x) {
        fuse_conn_info.congestion_threshold$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment reserved$slice(MemorySegment seg) {
        return seg.asSlice(36, 92);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


