// Generated by jextract

package org.cryptomator.jfuse.win.extr.fcntl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class fcntl_h  {

    public static final OfByte C_CHAR = JAVA_BYTE;
    public static final OfShort C_SHORT = JAVA_SHORT;
    public static final OfInt C_INT = JAVA_INT;
    public static final OfInt C_LONG = JAVA_INT;
    public static final OfLong C_LONG_LONG = JAVA_LONG;
    public static final OfFloat C_FLOAT = JAVA_FLOAT;
    public static final OfDouble C_DOUBLE = JAVA_DOUBLE;
    public static final AddressLayout C_POINTER = RuntimeHelper.POINTER;
    /**
     * {@snippet :
     * #define O_RDONLY 0
     * }
     */
    public static int O_RDONLY() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define O_WRONLY 1
     * }
     */
    public static int O_WRONLY() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define O_RDWR 2
     * }
     */
    public static int O_RDWR() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define O_APPEND 8
     * }
     */
    public static int O_APPEND() {
        return (int)8L;
    }
    /**
     * {@snippet :
     * #define O_CREAT 256
     * }
     */
    public static int O_CREAT() {
        return (int)256L;
    }
    /**
     * {@snippet :
     * #define O_TRUNC 512
     * }
     */
    public static int O_TRUNC() {
        return (int)512L;
    }
    /**
     * {@snippet :
     * #define O_EXCL 1024
     * }
     */
    public static int O_EXCL() {
        return (int)1024L;
    }
}


