// Generated by jextract

package org.cryptomator.jfuse.linux.amd64.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$7 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$7() {}
    static final VarHandle const$0 = constants$5.const$5.varHandle(MemoryLayout.PathElement.groupElement("__pad0"));
    static final VarHandle const$1 = constants$5.const$5.varHandle(MemoryLayout.PathElement.groupElement("st_rdev"));
    static final VarHandle const$2 = constants$5.const$5.varHandle(MemoryLayout.PathElement.groupElement("st_size"));
    static final VarHandle const$3 = constants$5.const$5.varHandle(MemoryLayout.PathElement.groupElement("st_blksize"));
    static final VarHandle const$4 = constants$5.const$5.varHandle(MemoryLayout.PathElement.groupElement("st_blocks"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_LONG.withName("f_bsize"),
        JAVA_LONG.withName("f_frsize"),
        JAVA_LONG.withName("f_blocks"),
        JAVA_LONG.withName("f_bfree"),
        JAVA_LONG.withName("f_bavail"),
        JAVA_LONG.withName("f_files"),
        JAVA_LONG.withName("f_ffree"),
        JAVA_LONG.withName("f_favail"),
        JAVA_LONG.withName("f_fsid"),
        JAVA_LONG.withName("f_flag"),
        JAVA_LONG.withName("f_namemax"),
        MemoryLayout.sequenceLayout(6, JAVA_INT).withName("__f_spare")
    ).withName("statvfs");
}


