// Generated by jextract

package org.cryptomator.jfuse.linux.amd64.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$37 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$37() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fuse_loop",
        constants$17.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "fuse_exit",
        constants$5.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "fuse_loop_mt",
        constants$18.const$3
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "fuse_get_session",
        constants$37.const$3
    );
}


