// Generated by jextract

package org.cryptomator.jfuse.linux.amd64.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$25 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$25() {}
    static final VarHandle const$0 = constants$14.const$4.varHandle(MemoryLayout.PathElement.groupElement("setxattr"));
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(fuse_operations.getxattr.class, "apply", constants$25.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$25.const$1
    );
    static final VarHandle const$4 = constants$14.const$4.varHandle(MemoryLayout.PathElement.groupElement("getxattr"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(fuse_operations.listxattr.class, "apply", constants$15.const$3);
}


