// Generated by jextract

package org.cryptomator.jfuse.linux.amd64.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$29 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$29() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$5.const$0
    );
    static final VarHandle const$1 = constants$14.const$4.varHandle(MemoryLayout.PathElement.groupElement("destroy"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(fuse_operations.access.class, "apply", constants$16.const$5);
    static final VarHandle const$3 = constants$14.const$4.varHandle(MemoryLayout.PathElement.groupElement("access"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(fuse_operations.create.class, "apply", constants$20.const$1);
    static final VarHandle const$5 = constants$14.const$4.varHandle(MemoryLayout.PathElement.groupElement("create"));
}


