// Generated by jextract

package org.cryptomator.jfuse.linux.amd64.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$12 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$12() {}
    static final VarHandle const$0 = constants$10.const$2.varHandle(MemoryLayout.PathElement.groupElement("intr"));
    static final VarHandle const$1 = constants$10.const$2.varHandle(MemoryLayout.PathElement.groupElement("intr_signal"));
    static final VarHandle const$2 = constants$10.const$2.varHandle(MemoryLayout.PathElement.groupElement("remember"));
    static final VarHandle const$3 = constants$10.const$2.varHandle(MemoryLayout.PathElement.groupElement("hard_remove"));
    static final VarHandle const$4 = constants$10.const$2.varHandle(MemoryLayout.PathElement.groupElement("use_ino"));
    static final VarHandle const$5 = constants$10.const$2.varHandle(MemoryLayout.PathElement.groupElement("readdir_ino"));
}


