// Generated by jextract

package org.cryptomator.jfuse.win.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$27 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$27() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(fuse3_operations.access.class, "apply", constants$14.const$2);
    static final VarHandle const$1 = constants$12.const$1.varHandle(MemoryLayout.PathElement.groupElement("access"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(fuse3_operations.create.class, "apply", constants$17.const$4);
    static final VarHandle const$3 = constants$12.const$1.varHandle(MemoryLayout.PathElement.groupElement("create"));
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(fuse3_operations.lock.class, "apply", constants$27.const$4);
}


