// Generated by jextract

package org.cryptomator.jfuse.win.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$32 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$32() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$31.const$4
    );
    static final VarHandle const$1 = constants$12.const$1.varHandle(MemoryLayout.PathElement.groupElement("fallocate"));
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "fuse3_lib_help",
        constants$26.const$2
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "fuse3_new",
        constants$32.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "fuse3_destroy",
        constants$26.const$2
    );
}


