// Generated by jextract

package org.cryptomator.jfuse.win.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$33 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$33() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fuse3_mount",
        constants$16.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "fuse3_unmount",
        constants$26.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "fuse3_loop",
        constants$15.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "fuse3_loop_mt_31",
        constants$14.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "fuse3_exit",
        constants$26.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "fuse3_get_session",
        constants$33.const$5
    );
}


