// Generated by jextract

package org.cryptomator.jfuse.win.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$12 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$12() {}
    static final VarHandle const$0 = constants$8.const$0.varHandle(MemoryLayout.PathElement.groupElement("debug"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("getattr"),
        RuntimeHelper.POINTER.withName("readlink"),
        RuntimeHelper.POINTER.withName("mknod"),
        RuntimeHelper.POINTER.withName("mkdir"),
        RuntimeHelper.POINTER.withName("unlink"),
        RuntimeHelper.POINTER.withName("rmdir"),
        RuntimeHelper.POINTER.withName("symlink"),
        RuntimeHelper.POINTER.withName("rename"),
        RuntimeHelper.POINTER.withName("link"),
        RuntimeHelper.POINTER.withName("chmod"),
        RuntimeHelper.POINTER.withName("chown"),
        RuntimeHelper.POINTER.withName("truncate"),
        RuntimeHelper.POINTER.withName("open"),
        RuntimeHelper.POINTER.withName("read"),
        RuntimeHelper.POINTER.withName("write"),
        RuntimeHelper.POINTER.withName("statfs"),
        RuntimeHelper.POINTER.withName("flush"),
        RuntimeHelper.POINTER.withName("release"),
        RuntimeHelper.POINTER.withName("fsync"),
        RuntimeHelper.POINTER.withName("setxattr"),
        RuntimeHelper.POINTER.withName("getxattr"),
        RuntimeHelper.POINTER.withName("listxattr"),
        RuntimeHelper.POINTER.withName("removexattr"),
        RuntimeHelper.POINTER.withName("opendir"),
        RuntimeHelper.POINTER.withName("readdir"),
        RuntimeHelper.POINTER.withName("releasedir"),
        RuntimeHelper.POINTER.withName("fsyncdir"),
        RuntimeHelper.POINTER.withName("init"),
        RuntimeHelper.POINTER.withName("destroy"),
        RuntimeHelper.POINTER.withName("access"),
        RuntimeHelper.POINTER.withName("create"),
        RuntimeHelper.POINTER.withName("lock"),
        RuntimeHelper.POINTER.withName("utimens"),
        RuntimeHelper.POINTER.withName("bmap"),
        RuntimeHelper.POINTER.withName("ioctl"),
        RuntimeHelper.POINTER.withName("poll"),
        RuntimeHelper.POINTER.withName("write_buf"),
        RuntimeHelper.POINTER.withName("read_buf"),
        RuntimeHelper.POINTER.withName("flock"),
        RuntimeHelper.POINTER.withName("fallocate")
    ).withName("fuse3_operations");
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(fuse3_operations.getattr.class, "apply", constants$12.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$12.const$2
    );
    static final VarHandle const$5 = constants$12.const$1.varHandle(MemoryLayout.PathElement.groupElement("getattr"));
}


