// Generated by jextract

package org.cryptomator.jfuse.win.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$23 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$23() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$22.const$4
    );
    static final VarHandle const$1 = constants$12.const$1.varHandle(MemoryLayout.PathElement.groupElement("getxattr"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(fuse3_operations.listxattr.class, "apply", constants$13.const$0);
    static final VarHandle const$3 = constants$12.const$1.varHandle(MemoryLayout.PathElement.groupElement("listxattr"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(fuse3_operations.removexattr.class, "apply", constants$16.const$0);
    static final VarHandle const$5 = constants$12.const$1.varHandle(MemoryLayout.PathElement.groupElement("removexattr"));
}


