// Generated by jextract

package org.cryptomator.jfuse.win.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct fuse3_loop_config {
 *     int clone_fd;
 *     unsigned int max_idle_threads;
 * };
 * }
 */
public class fuse3_loop_config {

    public static MemoryLayout $LAYOUT() {
        return constants$5.const$1;
    }
    public static VarHandle clone_fd$VH() {
        return constants$5.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int clone_fd;
     * }
     */
    public static int clone_fd(MemorySegment seg) {
        return (int)constants$5.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int clone_fd;
     * }
     */
    public static void clone_fd(MemorySegment seg, int x) {
        constants$5.const$2.set(seg, x);
    }
    public static int clone_fd(MemorySegment seg, long index) {
        return (int)constants$5.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void clone_fd(MemorySegment seg, long index, int x) {
        constants$5.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle max_idle_threads$VH() {
        return constants$5.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int max_idle_threads;
     * }
     */
    public static int max_idle_threads(MemorySegment seg) {
        return (int)constants$5.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int max_idle_threads;
     * }
     */
    public static void max_idle_threads(MemorySegment seg, int x) {
        constants$5.const$3.set(seg, x);
    }
    public static int max_idle_threads(MemorySegment seg, long index) {
        return (int)constants$5.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void max_idle_threads(MemorySegment seg, long index, int x) {
        constants$5.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


