// Generated by jextract

package org.cryptomator.jfuse.win.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct fuse3_file_info {
 *     int flags;
 *      *     unsigned int writepage;
 *     unsigned int direct_io;
 *     unsigned int keep_cache;
 *     unsigned int flush;
 *     unsigned int nonseekable;
 *     unsigned int flock_release;
 *     unsigned int padding;
 *     unsigned long long fh;
 *     unsigned long long lock_owner;
 *     unsigned int poll_events;
 * };
 * }
 */
public class fuse3_file_info {

    public static MemoryLayout $LAYOUT() {
        return constants$4.const$2;
    }
    public static VarHandle flags$VH() {
        return constants$4.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int flags;
     * }
     */
    public static int flags(MemorySegment seg) {
        return (int)constants$4.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int flags;
     * }
     */
    public static void flags(MemorySegment seg, int x) {
        constants$4.const$3.set(seg, x);
    }
    public static int flags(MemorySegment seg, long index) {
        return (int)constants$4.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void flags(MemorySegment seg, long index, int x) {
        constants$4.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle fh$VH() {
        return constants$4.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned long long fh;
     * }
     */
    public static long fh(MemorySegment seg) {
        return (long)constants$4.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned long long fh;
     * }
     */
    public static void fh(MemorySegment seg, long x) {
        constants$4.const$4.set(seg, x);
    }
    public static long fh(MemorySegment seg, long index) {
        return (long)constants$4.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void fh(MemorySegment seg, long index, long x) {
        constants$4.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle lock_owner$VH() {
        return constants$4.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned long long lock_owner;
     * }
     */
    public static long lock_owner(MemorySegment seg) {
        return (long)constants$4.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned long long lock_owner;
     * }
     */
    public static void lock_owner(MemorySegment seg, long x) {
        constants$4.const$5.set(seg, x);
    }
    public static long lock_owner(MemorySegment seg, long index) {
        return (long)constants$4.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void lock_owner(MemorySegment seg, long index, long x) {
        constants$4.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle poll_events$VH() {
        return constants$5.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int poll_events;
     * }
     */
    public static int poll_events(MemorySegment seg) {
        return (int)constants$5.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int poll_events;
     * }
     */
    public static void poll_events(MemorySegment seg, int x) {
        constants$5.const$0.set(seg, x);
    }
    public static int poll_events(MemorySegment seg, long index) {
        return (int)constants$5.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void poll_events(MemorySegment seg, long index, int x) {
        constants$5.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


