// Generated by jextract

package org.cryptomator.jfuse.win.extr.fuse3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct fuse_timespec {
 *     long long tv_sec;
 *     long long tv_nsec;
 * };
 * }
 */
public class fuse_timespec {

    public static MemoryLayout $LAYOUT() {
        return constants$0.const$0;
    }
    public static VarHandle tv_sec$VH() {
        return constants$0.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * long long tv_sec;
     * }
     */
    public static long tv_sec(MemorySegment seg) {
        return (long)constants$0.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * long long tv_sec;
     * }
     */
    public static void tv_sec(MemorySegment seg, long x) {
        constants$0.const$1.set(seg, x);
    }
    public static long tv_sec(MemorySegment seg, long index) {
        return (long)constants$0.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void tv_sec(MemorySegment seg, long index, long x) {
        constants$0.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle tv_nsec$VH() {
        return constants$0.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * long long tv_nsec;
     * }
     */
    public static long tv_nsec(MemorySegment seg) {
        return (long)constants$0.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * long long tv_nsec;
     * }
     */
    public static void tv_nsec(MemorySegment seg, long x) {
        constants$0.const$2.set(seg, x);
    }
    public static long tv_nsec(MemorySegment seg, long index) {
        return (long)constants$0.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void tv_nsec(MemorySegment seg, long index, long x) {
        constants$0.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


