// Generated by jextract

package org.cryptomator.jfuse.linux.aarch64.extr;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class fcntl_h  {

    public static final OfByte C_CHAR = Constants$root.C_CHAR$LAYOUT;
    public static final OfShort C_SHORT = Constants$root.C_SHORT$LAYOUT;
    public static final OfInt C_INT = Constants$root.C_INT$LAYOUT;
    public static final OfLong C_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static final OfLong C_LONG_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static final OfFloat C_FLOAT = Constants$root.C_FLOAT$LAYOUT;
    public static final OfDouble C_DOUBLE = Constants$root.C_DOUBLE$LAYOUT;
    public static final OfAddress C_POINTER = Constants$root.C_POINTER$LAYOUT;
    /**
     * {@snippet :
     * #define O_RDONLY 0
     * }
     */
    public static int O_RDONLY() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define O_WRONLY 1
     * }
     */
    public static int O_WRONLY() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define O_RDWR 2
     * }
     */
    public static int O_RDWR() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define O_CREAT 64
     * }
     */
    public static int O_CREAT() {
        return (int)64L;
    }
    /**
     * {@snippet :
     * #define O_EXCL 128
     * }
     */
    public static int O_EXCL() {
        return (int)128L;
    }
    /**
     * {@snippet :
     * #define O_TRUNC 512
     * }
     */
    public static int O_TRUNC() {
        return (int)512L;
    }
    /**
     * {@snippet :
     * #define O_APPEND 1024
     * }
     */
    public static int O_APPEND() {
        return (int)1024L;
    }
    /**
     * {@snippet :
     * #define O_SYNC 1052672
     * }
     */
    public static int O_SYNC() {
        return (int)1052672L;
    }
    /**
     * {@snippet :
     * #define O_DSYNC 4096
     * }
     */
    public static int O_DSYNC() {
        return (int)4096L;
    }
}


